'use strict';

const SURAHS = [
  { n: 1,   ar: 'الفاتحة',      en: 'Al-Fatihah' },
  { n: 2,   ar: 'البقرة',        en: 'Al-Baqarah' },
  { n: 3,   ar: 'آل عمران',      en: "Ali 'Imran" },
  { n: 4,   ar: 'النساء',        en: 'An-Nisa' },
  { n: 5,   ar: 'المائدة',       en: "Al-Ma'idah" },
  { n: 6,   ar: 'الأنعام',       en: "Al-An'am" },
  { n: 7,   ar: 'الأعراف',       en: "Al-A'raf" },
  { n: 8,   ar: 'الأنفال',       en: 'Al-Anfal' },
  { n: 9,   ar: 'التوبة',        en: 'At-Tawbah' },
  { n: 10,  ar: 'يونس',          en: 'Yunus' },
  { n: 11,  ar: 'هود',           en: 'Hud' },
  { n: 12,  ar: 'يوسف',          en: 'Yusuf' },
  { n: 13,  ar: 'الرعد',         en: "Ar-Ra'd" },
  { n: 14,  ar: 'إبراهيم',       en: 'Ibrahim' },
  { n: 15,  ar: 'الحجر',         en: 'Al-Hijr' },
  { n: 16,  ar: 'النحل',         en: 'An-Nahl' },
  { n: 17,  ar: 'الإسراء',       en: 'Al-Isra' },
  { n: 18,  ar: 'الكهف',         en: 'Al-Kahf' },
  { n: 19,  ar: 'مريم',          en: 'Maryam' },
  { n: 20,  ar: 'طه',            en: 'Taha' },
  { n: 21,  ar: 'الأنبياء',      en: 'Al-Anbiya' },
  { n: 22,  ar: 'الحج',          en: 'Al-Hajj' },
  { n: 23,  ar: 'المؤمنون',      en: "Al-Mu'minun" },
  { n: 24,  ar: 'النور',         en: 'An-Nur' },
  { n: 25,  ar: 'الفرقان',       en: 'Al-Furqan' },
  { n: 26,  ar: 'الشعراء',       en: "Ash-Shu'ara" },
  { n: 27,  ar: 'النمل',         en: 'An-Naml' },
  { n: 28,  ar: 'القصص',         en: 'Al-Qasas' },
  { n: 29,  ar: 'العنكبوت',      en: "Al-'Ankabut" },
  { n: 30,  ar: 'الروم',         en: 'Ar-Rum' },
  { n: 31,  ar: 'لقمان',         en: 'Luqman' },
  { n: 32,  ar: 'السجدة',        en: 'As-Sajdah' },
  { n: 33,  ar: 'الأحزاب',       en: 'Al-Ahzab' },
  { n: 34,  ar: 'سبأ',           en: "Saba'" },
  { n: 35,  ar: 'فاطر',          en: 'Fatir' },
  { n: 36,  ar: 'يس',            en: 'Ya-Sin' },
  { n: 37,  ar: 'الصافات',       en: 'As-Saffat' },
  { n: 38,  ar: 'ص',             en: 'Sad' },
  { n: 39,  ar: 'الزمر',         en: 'Az-Zumar' },
  { n: 40,  ar: 'غافر',          en: 'Ghafir' },
  { n: 41,  ar: 'فصلت',          en: 'Fussilat' },
  { n: 42,  ar: 'الشورى',        en: 'Ash-Shuraa' },
  { n: 43,  ar: 'الزخرف',        en: 'Az-Zukhruf' },
  { n: 44,  ar: 'الدخان',        en: 'Ad-Dukhan' },
  { n: 45,  ar: 'الجاثية',       en: 'Al-Jathiyah' },
  { n: 46,  ar: 'الأحقاف',       en: 'Al-Ahqaf' },
  { n: 47,  ar: 'محمد',          en: 'Muhammad' },
  { n: 48,  ar: 'الفتح',         en: 'Al-Fath' },
  { n: 49,  ar: 'الحجرات',       en: 'Al-Hujurat' },
  { n: 50,  ar: 'ق',             en: 'Qaf' },
  { n: 51,  ar: 'الذاريات',      en: 'Adh-Dhariyat' },
  { n: 52,  ar: 'الطور',         en: 'At-Tur' },
  { n: 53,  ar: 'النجم',         en: 'An-Najm' },
  { n: 54,  ar: 'القمر',         en: 'Al-Qamar' },
  { n: 55,  ar: 'الرحمن',        en: 'Ar-Rahman' },
  { n: 56,  ar: 'الواقعة',       en: "Al-Waqi'ah" },
  { n: 57,  ar: 'الحديد',        en: 'Al-Hadid' },
  { n: 58,  ar: 'المجادلة',      en: 'Al-Mujadila' },
  { n: 59,  ar: 'الحشر',         en: 'Al-Hashr' },
  { n: 60,  ar: 'الممتحنة',      en: 'Al-Mumtahanah' },
  { n: 61,  ar: 'الصف',          en: 'As-Saf' },
  { n: 62,  ar: 'الجمعة',        en: "Al-Jumu'ah" },
  { n: 63,  ar: 'المنافقون',     en: 'Al-Munafiqun' },
  { n: 64,  ar: 'التغابن',       en: 'At-Taghabun' },
  { n: 65,  ar: 'الطلاق',        en: 'At-Talaq' },
  { n: 66,  ar: 'التحريم',       en: 'At-Tahrim' },
  { n: 67,  ar: 'الملك',         en: 'Al-Mulk' },
  { n: 68,  ar: 'القلم',         en: 'Al-Qalam' },
  { n: 69,  ar: 'الحاقة',        en: 'Al-Haqqah' },
  { n: 70,  ar: 'المعارج',       en: "Al-Ma'arij" },
  { n: 71,  ar: 'نوح',           en: 'Nuh' },
  { n: 72,  ar: 'الجن',          en: 'Al-Jinn' },
  { n: 73,  ar: 'المزمل',        en: 'Al-Muzzammil' },
  { n: 74,  ar: 'المدثر',        en: 'Al-Muddaththir' },
  { n: 75,  ar: 'القيامة',       en: 'Al-Qiyamah' },
  { n: 76,  ar: 'الإنسان',       en: 'Al-Insan' },
  { n: 77,  ar: 'المرسلات',      en: 'Al-Mursalat' },
  { n: 78,  ar: 'النبأ',         en: "An-Naba'" },
  { n: 79,  ar: 'النازعات',      en: "An-Nazi'at" },
  { n: 80,  ar: 'عبس',           en: "'Abasa" },
  { n: 81,  ar: 'التكوير',       en: 'At-Takwir' },
  { n: 82,  ar: 'الانفطار',      en: 'Al-Infitar' },
  { n: 83,  ar: 'المطففين',      en: 'Al-Mutaffifin' },
  { n: 84,  ar: 'الانشقاق',      en: 'Al-Inshiqaq' },
  { n: 85,  ar: 'البروج',        en: 'Al-Buruj' },
  { n: 86,  ar: 'الطارق',        en: 'At-Tariq' },
  { n: 87,  ar: 'الأعلى',        en: "Al-A'la" },
  { n: 88,  ar: 'الغاشية',       en: 'Al-Ghashiyah' },
  { n: 89,  ar: 'الفجر',         en: 'Al-Fajr' },
  { n: 90,  ar: 'البلد',         en: 'Al-Balad' },
  { n: 91,  ar: 'الشمس',         en: 'Ash-Shams' },
  { n: 92,  ar: 'الليل',         en: 'Al-Layl' },
  { n: 93,  ar: 'الضحى',         en: 'Ad-Duha' },
  { n: 94,  ar: 'الشرح',         en: 'Ash-Sharh' },
  { n: 95,  ar: 'التين',         en: 'At-Tin' },
  { n: 96,  ar: 'العلق',         en: "Al-'Alaq" },
  { n: 97,  ar: 'القدر',         en: 'Al-Qadr' },
  { n: 98,  ar: 'البينة',        en: 'Al-Bayyinah' },
  { n: 99,  ar: 'الزلزلة',       en: 'Az-Zalzalah' },
  { n: 100, ar: 'العاديات',      en: "Al-'Adiyat" },
  { n: 101, ar: 'القارعة',       en: "Al-Qari'ah" },
  { n: 102, ar: 'التكاثر',       en: 'At-Takathur' },
  { n: 103, ar: 'العصر',         en: "Al-'Asr" },
  { n: 104, ar: 'الهمزة',        en: 'Al-Humazah' },
  { n: 105, ar: 'الفيل',         en: 'Al-Fil' },
  { n: 106, ar: 'قريش',          en: 'Quraysh' },
  { n: 107, ar: 'الماعون',       en: "Al-Ma'un" },
  { n: 108, ar: 'الكوثر',        en: 'Al-Kawthar' },
  { n: 109, ar: 'الكافرون',      en: 'Al-Kafirun' },
  { n: 110, ar: 'النصر',         en: 'An-Nasr' },
  { n: 111, ar: 'المسد',         en: 'Al-Masad' },
  { n: 112, ar: 'الإخلاص',       en: 'Al-Ikhlas' },
  { n: 113, ar: 'الفلق',         en: 'Al-Falaq' },
  { n: 114, ar: 'الناس',         en: 'An-Nas' },
];

const surahMap = new Map(SURAHS.map(s => [s.n, s]));

function getSurah(number) {
  return surahMap.get(number) || { n: number, ar: `سورة ${number}`, en: `Surah ${number}` };
}

module.exports = { SURAHS, getSurah };
